name = "SOCRATESSingleColumnForcings"
uuid = "efca6b66-9b98-11ed-1a32-7b7cdccd517a"
authors = ["Jordan Benjamin"]
version = "0.14.0"

[deps]
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
LazyArtifacts = "4af54fe1-eca0-43a8-85a7-787d91b784e3"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[weakdeps]
Thermodynamics = "b60c26fb-14c3-4610-9d3e-2d17fe7ff00c"
NonNegLeastSquares = "b7351bd1-99d9-5c5d-8786-f205a815c4d7"
PCHIPInterpolation = "afe20452-48d1-4729-9a8b-50fb251f06cd"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Dierckx = "39dd38d3-220a-591b-8e3c-4c3a8c710a94"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"


[extensions]
SOCRATESSingleColumnForcingsDierckxExt = ["Dierckx"]
SOCRATESSingleColumnForcingsInterpolationsExt = ["Interpolations"]
SOCRATESSingleColumnForcingsNonNegLeastSquaresExt = ["NonNegLeastSquares"]
SOCRATESSingleColumnForcingsPCHIPInterpolationExt = ["PCHIPInterpolation", "ForwardDiff"]
SOCRATESSingleColumnForcingsThermodynamicsExt = ["Thermodynamics"]

[compat]
Artifacts = "1"
Dates = "1"
DelimitedFiles = "1"
Dierckx = "0.5"
Downloads = "1"
ForwardDiff = "0.10, 1"
Interpolations = "0.16"
LazyArtifacts = "1"
LinearAlgebra = "1"
NCDatasets = "0.14"
NonNegLeastSquares = "0.4"
PCHIPInterpolation = "0.2"
Pkg = "1"
StaticArrays = "1.2"
Statistics = "1"
Thermodynamics = "0.11, 0.12, 0.13, 0.14, 0.15"
julia = "1.10"


[workspace]
projects = ["test", "docs"]
